name: Scheduled Prayer Times Checker
on:
  schedule:
    - cron: "0 9 * * *"  # Runs every day at 09:00 UTC
  workflow_dispatch:  # Allows manual trigger
    
jobs:
  run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Run Docker Container
        run: |
          docker pull billo1w/prayertimeschecker
          docker run billo1w/prayertimeschecker
